services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "${FLASK_PORT}:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
  
  rabbitmq:
    image: rabbitmq:4.1.4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}   
    ports:
      - "${RABBITMQ_PORT}:5672"          # основной порт AMQP
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"  # порт веб-админки
    networks:
      - default

networks:
  default:
    driver: bridge