services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "${FLASK_PORT}:5000"
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_HOST: ${FLASK_HOST}
      FLASK_PORT: ${FLASK_PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
  
  rabbitmq:
    image: rabbitmq:4.1.4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}   
    ports:
      - "${RABBITMQ_PORT}:5672"          # основной порт AMQP
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"  # порт веб-админки
    networks:
      - default
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}       
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_DB: ${POSTGRES_DB}            
    ports:
      - "${POSTGRES_PORT}:5432"
    # Используем tmpfs для пересоздания БД каждый раз
    tmpfs:
      - /var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge